Fix not-null constraint errors
This was causing many tests to fail with:

ERROR: null value in column "p2pv2_bootstrappers" of relation "ocr_oracle_specs" violates not-null constraint (SQLSTATE 23502)